# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  financialcontrol:
    image: financialcontrol
    build:
      context: .
      dockerfile: financial-control/Dockerfile
    ports:
      - 5044:5044
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financialcontrol
    ports:
      - 5432:5432