# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DbFinancial
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - FinancialNet
  app:
    image: letodev/financial-image
    build:
      context: .
      dockerfile: financial-control/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5044:5044
    environment:
      ConnectionStrings:DbFinancial: "Host=postgres;Port=5432;Database=DbFinancial;Username=admin;Password=admin"
      RABBITMQ:HOSTNAME: "rabbitmq"
      RABBITMQ:USERNAME: "admin"
      RABBITMQ:PASSWORD: "admin"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - FinancialNet
    depends_on:
      postgres:
        condition: service_healthy
networks:
  FinancialNet:
    driver: bridge
