services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DbFinancial
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - FinancialNet
  app:
    image: letodev/financial-image
    build:
      context: .
      dockerfile: financial-control/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5044:5044
    environment:
      ConnectionStrings:DbFinancial: "Host=postgres;Port=5432;Database=DbFinancial;Username=admin;Password=admin"
      RABBITMQ:HOSTNAME: "rabbitmq"
      RABBITMQ:USERNAME: "admin"
      RABBITMQ:PASSWORD: "admin"
      RABBITMQ:PORT: "5672"
      RABBITMQ:EXCHANGE: "financial-exchange"
      RABBITMQ:QUEUE: "financial-queue"
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ:ConnectionString: "amqp://admin:admin@rabbitmq:5672/"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - FinancialNet
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - FinancialNet
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
networks:
  FinancialNet:
    driver: bridge
