# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  financialcontrol:
    image: financialcontrol
    build:
      context: .
      dockerfile: financial-control/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5044:5044
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
