services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DbFinancial
    ports:
      - 5432:5432
    networks:
      - financialNetwork
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s 
      retries: 5
      timeout: 10s
  app:
    image: letodev/financial-image
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8080:8080" # Port for debugging
    volumes:
      - .:/app
      - ~/.vsdbg:/root/.vsdbg # Debugger
    command: ["dotnet", "watch", "run", "--no-launch-profile"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - financialNetwork
networks:
  financialNetwork:
    driver: bridge