services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financialcontrol
    ports:
      - 5432:5432
    networks:
      - financialNetwork
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    ports:
      - "5000:5000"
      - "5001:5001"
      - "9229:9229" # Port for debugging
    volumes:
      - .:/app
      - ~/.vsdbg:/root/.vsdbg # Debugger
    command: ["dotnet", "watch", "run", "--no-launch-profile"]
    depends_on:
      - postgres
networks:
  financialNetwork:
    driver: bridge