// <auto-generated />
using System;
using FinancialControl.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialControl.API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260217193416_AddFKPersonInTransactionTable")]
    partial class AddFKPersonInTransactionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("LongName")
                        .HasColumnType("text");

                    b.Property<double>("MarketCap")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.AssetHistoricalValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AdjustedClose")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<double>("Close")
                        .HasColumnType("double precision");

                    b.Property<int>("Date")
                        .HasColumnType("integer");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetHistoricalValues");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.CashDividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetIssued")
                        .HasColumnType("text");

                    b.Property<Guid>("DividendsDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("IsinCode")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastDatePrior")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("RelatedTo")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DividendsDataId");

                    b.ToTable("CashDividends");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.DividendsData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("DividendsData");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonWalletId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonWalletId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.PersonWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("WalletId");

                    b.ToTable("PersonWallets");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Revenue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecurrent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Revenues");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.StockDividend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetIssued")
                        .HasColumnType("text");

                    b.Property<string>("CompleteFactor")
                        .HasColumnType("text");

                    b.Property<Guid>("DividendsDataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Factor")
                        .HasColumnType("integer");

                    b.Property<string>("IsinCode")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastDatePrior")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DividendsDataId");

                    b.ToTable("StockDividends");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.WalletAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId1");

                    b.ToTable("WalletAssets");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.AssetHistoricalValue", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Asset", "Asset")
                        .WithMany("HistoricalData")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.CashDividend", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.DividendsData", "DividendsData")
                        .WithMany("CashDividends")
                        .HasForeignKey("DividendsDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DividendsData");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.DividendsData", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Asset", "Asset")
                        .WithOne("DividendsData")
                        .HasForeignKey("FinancialControl.API.Data.Entities.DividendsData", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Order", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.PersonWallet", "PersonWallet")
                        .WithMany()
                        .HasForeignKey("PersonWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonWallet");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.PersonWallet", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialControl.API.Data.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.StockDividend", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.DividendsData", "DividendsData")
                        .WithMany("StockDividends")
                        .HasForeignKey("DividendsDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DividendsData");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Transaction", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Person", "Person")
                        .WithMany("Transactions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Wallet", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Person", null)
                        .WithMany("Wallets")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.WalletAsset", b =>
                {
                    b.HasOne("FinancialControl.API.Data.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialControl.API.Data.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialControl.API.Data.Entities.Wallet", null)
                        .WithMany("WalletAsset")
                        .HasForeignKey("WalletId1");

                    b.Navigation("Asset");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Asset", b =>
                {
                    b.Navigation("DividendsData");

                    b.Navigation("HistoricalData");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.DividendsData", b =>
                {
                    b.Navigation("CashDividends");

                    b.Navigation("StockDividends");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Person", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FinancialControl.API.Data.Entities.Wallet", b =>
                {
                    b.Navigation("WalletAsset");
                });
#pragma warning restore 612, 618
        }
    }
}
