@FinancialControl.API_HostAddress = http://localhost:5207

### Assets

# Get all assets
GET {{FinancialControl.API_HostAddress}}/assets
###

# Get assets with pagination
GET {{FinancialControl.API_HostAddress}}/assets:list?page=0&pageSize=10
###

# Get asset by id
GET {{FinancialControl.API_HostAddress}}/assets/00000000-0000-0000-0000-000000000000
###

# Create asset
POST {{FinancialControl.API_HostAddress}}/assets
Content-Type: application/json

{
  "description": "string",
  "code": "string",
  "type": "string"
}
###

# Update asset
PUT {{FinancialControl.API_HostAddress}}/assets/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "description": "string",
  "code": "string",
  "type": "string"
}
###

# Delete asset
DELETE {{FinancialControl.API_HostAddress}}/assets/00000000-0000-0000-0000-000000000000
###

### Movements

# Get all movements
GET {{FinancialControl.API_HostAddress}}/movements
###

# Get movements with pagination
GET {{FinancialControl.API_HostAddress}}/movements:list?page=0&pageSize=10
###

# Get movement by id
GET {{FinancialControl.API_HostAddress}}/movements/00000000-0000-0000-0000-000000000000
###

# Create movement
{
  "description": "string",
  "value": 0,
  "date": "2025-11-29T20:15:49.559Z"
}
###

# Update movement
PUT {{FinancialControl.API_HostAddress}}/movements/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "description": "string",
  "value": 0,
  "date": "2025-11-29T20:15:49.559Z"
}
###

# Delete movement
DELETE {{FinancialControl.API_HostAddress}}/movements/00000000-0000-0000-0000-000000000000
###

### Orders

# Get all orders
GET {{FinancialControl.API_HostAddress}}/orders
###

# Get orders with pagination
GET {{FinancialControl.API_HostAddress}}/orders:list?page=0&pageSize=10
###

# Get order by id
GET {{FinancialControl.API_HostAddress}}/orders/00000000-0000-0000-0000-000000000000
###

# Create order
POST {{FinancialControl.API_HostAddress}}/orders
Content-Type: application/json

{
  "peopleWalletId": "00000000-0000-0000-0000-000000000000",
  "date": "2025-11-29T20:15:49.559Z",
  "quantity": 0,
  "price": 0,
  "type": "string"
}
###

# Update order
PUT {{FinancialControl.API_HostAddress}}/orders/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "peopleWalletId": "00000000-0000-0000-0000-000000000000",
  "date": "2025-11-29T20:15:49.559Z",
  "quantity": 0,
  "price": 0,
  "type": "string"
}
###

# Delete order
DELETE {{FinancialControl.API_HostAddress}}/orders/00000000-0000-0000-0000-000000000000
###

### People

# Get all people
GET {{FinancialControl.API_HostAddress}}/people
###

# Get people with pagination
GET {{FinancialControl.API_HostAddress}}/people:list?page=0&pageSize=10
###

# Get person by id
GET {{FinancialControl.API_HostAddress}}/people/00000000-0000-0000-0000-000000000000
###

# Create person
POST {{FinancialControl.API_HostAddress}}/people
Content-Type: application/json

{
  "name": "string"
}
###

# Update person
PUT {{FinancialControl.API_HostAddress}}/people/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "name": "string"
}
###

# Delete person
DELETE {{FinancialControl.API_HostAddress}}/people/00000000-0000-0000-0000-000000000000
###

### Revenue

# Get all revenue
GET {{FinancialControl.API_HostAddress}}/revenue
###

# Get revenue with pagination
GET {{FinancialControl.API_HostAddress}}/revenue:list?page=0&pageSize=10
###

# Get revenue by id
GET {{FinancialControl.API_HostAddress}}/revenue/00000000-0000-0000-0000-000000000000
###

# Create revenue
POST {{FinancialControl.API_HostAddress}}/revenue
Content-Type: application/json

{
  "description": "string",
  "value": 0,
  "date": "2025-11-29T20:15:49.559Z"
}
###

# Update revenue
PUT {{FinancialControl.API_HostAddress}}/revenue/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "description": "string",
  "value": 0,
  "date": "2025-11-29T20:15:49.559Z"
}
###

# Delete revenue
DELETE {{FinancialControl.API_HostAddress}}/revenue/00000000-0000-0000-0000-000000000000
###

### Wallets

# Get all wallets
GET {{FinancialControl.API_HostAddress}}/wallets
###

# Get wallets with pagination
GET {{FinancialControl.API_HostAddress}}/wallet:list?page=0&pageSize=10
###

# Get wallet by id
GET {{FinancialControl.API_HostAddress}}/wallets/00000000-0000-0000-0000-000000000000
###

# Create wallet
POST {{FinancialControl.API_HostAddress}}/wallets
Content-Type: application/json

{
  "description": "string",
  "status": true
}
###

# Update wallet
PUT {{FinancialControl.API_HostAddress}}/wallets/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "description": "string",
  "status": true
}
###

# Delete wallet
DELETE {{FinancialControl.API_HostAddress}}/wallets/00000000-0000-0000-0000-000000000000
###